name: Logic App Infrastructure as Code Pipeline. 

on:
  workflow_dispatch:
  push:
    paths:
      - "ARM/**"
      - ".github/workflows/IaC_deploy.yml"
      

jobs:
  DeployDev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    environment: 
      name: Dev
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
        enable-AzPSSession: true 

    # Checkout
    - name: Checkout
      uses: actions/checkout@v1

    # Deployment of template  
    - name: Deploy Logic App Resources
      uses: Azure/arm-deploy@v1.0.1
      id: ladeploy
      with:
        # You can change these environment variables for your configuration:   AZURE_SUBSCRIPTION_ID, AZURE_RESOURCE_GROUP
        scope: resourcegroup  
        subscriptionId: ${{ secrets.AZURE_SUB }}
        resourceGroupName:  ${{ secrets.RG_LA }}
        template: ARM/la-template.json  # Set this to the location of your template file
        parameters: ARM/la-parameters.json # Set this to the location of your parameters file
        deploymentMode: Incremental
   
 